### ISSUE TITLE
openwrt-22.03使用infinityfreedom主题编译出来的固件页面报错

### ISSUE THREAD

**Issue by zhengxiang311019** [xiaoqingfengATGH/luci-theme-infinityfreedom#21]
报错内容具体如下：
/usr/lib/lua/luci/template.lua:97: Failed to execute template 'sysauth'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'header'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/infinityfreedom/header'.
A runtime error occurred: [string "/usr/lib/lua/luci/view/themes/infinityfreed..."]:23: attempt to call field 'node_childs' (a nil value)
stack traceback:
	[string "/usr/lib/lua/luci/view/themes/infinityfreed..."]:23: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:700: in function 'include'
	[string "/usr/lib/lua/luci/view/header.htm"]:3: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:700: in function 'include'
	[string "/usr/lib/lua/luci/view/sysauth.htm"]:1: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function </usr/lib/lua/luci/template.lua:85>
	(tail call): ?
	(tail call): ?
	/usr/lib/lua/luci/dispatcher.lua:483: in function </usr/lib/lua/luci/dispatcher.lua:482>

但是切换成其他openwrt内置主题可以正常使用。请问这个是什么原因啊？

**Comment by lokisama** [comment]
中文README写着 暂时只支持luci版本18..看源码感觉其实很快可以改到22

**Comment by zhengxiang311019** [comment]
> 中文README写着 暂时只支持luci版本18..看源码感觉其实很快可以改到22

好的，谢谢
